### ISSUE TITLE
VT52 waiting for valid escape sequence

### ISSUE THREAD

**Issue by ivop** [davidgiven/cpm65#107]
Hi,

First of all, I'm very pleased to see that VT52 was turned into a loadable driver. Very nice!

The question was asked how to print escape from Altirra BASIC. That can be done with chr$(). For example:

```
? chr$(27);"H";chr$(27);"J"
```

To home the cursor and clear screen.

I noticed that when an invalid escape sequence is encountered, it keeps waiting for a valid one. `? chr$(27)` &lt;enter&gt; and nothing gets echoed to the screen anymore (but Altirra's input routine does receive the characters). After typing `H` it "escapes" from that state and everything turns to normal again.

@davidgiven How does one exit atbasic? I can't get out of it! :)

**Comment by venomix666** [comment]
Thank you for reporting this.

I missed to handle the invalid escape sequence case in the driver code, I will fix this and submit a pull request.
