### ISSUE TITLE
cpm.h header file needed

### ISSUE THREAD

**Issue by mrgw454** [davidgiven/cpm65#129]
Trying to build this project and running into an issue where a cpm.h header file is needed.  I have a few (including from the z88dk library) but want to make sure I'm using the correct one.

Thanks for any help you can provide.

-Ron

**Comment by davidgiven** [comment]
It should be found automatically by llvm-mos (it's part of the CP/M-65 llvm-mos runtime library). You might want to check your llvm-mos installation.

**Comment by mrgw454** [comment]
You were correct -- I still needed to build the llvm-mos-sdk project.  I was able to get past this issue.

Thanks for the quick response!

-Ron
