### ISSUE TITLE
Apple IIe version does not do LineFeed when using the STAT Program on the Virtual II Emulator

### ISSUE THREAD

**Issue by callapple** [davidgiven/cpm65#14]
When I ran the STAT program on the Virtual II Emulator (MAC OS), the output from STAT just over prints each line of the output and then places a PROMPT in col 1 instead of 0.

**Comment by davidgiven** [comment]
Yes, this is a now-fixed bug in llvm-mos: https://github.com/llvm-mos/llvm-mos-sdk/pull/112 (Or, more accurately, in some of my cpm65 tooling in llvm-mos.) The fix has been merged so once they make a release this should go away.

**Comment by davidgiven** [comment]
Duplicate: https://github.com/llvm-mos/llvm-mos-sdk/pull/112
