### ISSUE TITLE
No Binary for Nano6502?

### ISSUE THREAD

**Issue by okwatts** [davidgiven/cpm65#147]
Not a bug but more a question about the lack of a binary for the Nano6502. Should I be bugging the creator of this or is there no auto make as part of your scripts? I wanted to try this out before investing in setting up the lvm-mos environment. Thanks

**Comment by davidgiven** [comment]
Oops, they didn't get added to the release scripts. Fixed now.

**Comment by okwatts** [comment]
Thanks works great. Now to learn more.
