### ISSUE TITLE
Hitting ctrl+c while on a different user area crashes CP/M-65

### ISSUE THREAD

**Issue by venomix666** [davidgiven/cpm65#169]
I accidently hit ctrl+c while on user area 1 on the nano6502, and this crashed CP/M-65 with the error message "Couldn't open CCP". I could recreate the same thing on a BBC Micro (with b-em) to verify that it is not  platform specific.

I haven't investigated further, but I assume it tries to load CCP from the current user area and fails.

**Comment by davidgiven** [comment]
Thanks for the bug report. That's extremely likely. User areas are cursed; I'll take a look.
