### ISSUE TITLE
Bug in CCP?

### ISSUE THREAD

**Issue by ivop** [davidgiven/cpm65#31]
Hi,

I'm observing strange behaviour with CCP. It seems there are leftover bytes from previous commands.

A>bug z*
Z???????
A>dir *.txt
A: ASM    TXT : BEDIT   TXT
A>bug z*
Z???????TXT
A>bug zzzzz*
ZZZZZ???K??

Here's the code of bug:

```
.bss pblock, 165
cpm_fcb = pblock

BDOS_CONOUT = 2
BDOS = start - 3

    .zp savex,1

start:
    ldx #0

    .zrepeat
        lda cpm_fcb+1,x

        ldy #BDOS_CONOUT
        stx savex
        jsr BDOS
        ldx savex
        inx
        cpx #11
    .zuntil eq

    lda #13
    ldy #BDOS_CONOUT
    jsr BDOS

    lda #10
    ldy #BDOS_CONOUT
    jmp BDOS
```

Looking over ccp.S it looks like the fcb is properly cleared, but somewhere weird values are written to it. I specifically wrote bug with asm as to rule out the llvm toolchain. Any ideas?

**Comment by davidgiven** [comment]
I bet I know what's going on here --- expanding wildcards for a filename with no extension doesn't overwrite the extension. (For `z*` you should get `Z???????.   `.)

Filename parsing is so awful I wonder whether it's worth adding a BDOS function for it so there's only one piece of code which needs to be right. CP/M 3 had one...
