### ISSUE TITLE
cpm_ram and gettpa behaviour

### ISSUE THREAD

**Issue by ivop** [davidgiven/cpm65#43]
Hi,

I stumbled upon some strange behaviour which I cannot explain.

See this code in my test branch: https://github.com/ivop/cpm65/blob/test/apps/test.c

Output:

```
    CP/M-65 for the Atari 800                   
                                                
    A>free                                      
    ZP: 95 to FF. Free: 6A                      
    TPA: 1900 to BC00. Free: A300               
    CCP at: B200                                
    A>test                                      
    start: 9500                                 
    cpm▁ram: 3790                               
    end: ff00                                   
    A>                                          
```

```
$ xxd -s 1 -l 1 .obj/test.com
00000001: 21                                       !
```

Any idea what's going on?

I was compiling a pretty large program and cpm_ram ended up somewhere in the middle of my code.

I have confirmed this with the BBC and Apple][ port.

Regards,
Ivo

Edit: this large program: https://github.com/ivop/cpm65/blob/ubasic/apps/ubasic.c

With a hardcoded higher address it runs. Not that it's a particularly useful basic. It completely lacks syntax errors and is pretty useless, and I won't pursue that path any further, but I was flabbergasted by the weird values of tpa_start and cpm_ram.

I also briefly looked into Palo Alto's Tiny Basic, but that one has no tokenizer.

Microsoft Basic's disassembled source is available in various versions, but that looks daunting to port (CA65 assembly with lots of defines and macro's). Perhaps Altirra Basic. That one is a reimplementation of Atari Basic, open source, 8kB binary, and actively maintained. Rip out the Atari specific stuff like graphics commands, and it could be a viable candidate. Or the Microsoft Basic compatible from "the other CPM-65".

**Comment by davidgiven** [comment]
The most likely explanation is that the C bindings are using the wrong BDOS entrypoint numbers and have ZP and TPA swapped. It would actually be easier to change the BDOS itself...

**Comment by ivop** [comment]
You are correct.

calling cpm_bios_gettpa() results in:

```
    CP/M-65 for the Atari 800                   
                                                
    A>test                                      
    start: 1900                                 
    cpm▁ram: 3790                               
    end: bc00                                   
    A>                                          
```

Still, I expected the start address being updated by CCP before calling the loaded application, so you can easily chain load overlays if you want to. Is this intended behaviour?

**Comment by davidgiven** [comment]
Fixed.

Re the CCP not updating the start/end address: that's intentional, as it makes it easier to know when the application has changed one of the addresses if it, e.g., wants to install a TSR. Adjusting it doesn't help much for overlays as only the application knows how much heap memory it needs.

There really needs to be some proper documentation...

**Comment by ivop** [comment]
Thanks!
