### ISSUE TITLE
Memory banking issue in Apple 2e

### ISSUE THREAD

**Issue by univta0001** [davidgiven/cpm65#54]
In the Apple 2e CPM-65, it is not working in Apple 22JSE (https://www.scullinsteel.com/apple/e) because the bank switch is not working.

The source code is using two STA $C08b to switch the bank. Based on "Understanding the Apple IIe, by James Fielding Sather, Pg 5-24", bank switch should only work with reading twice on $C08b. Manually changing editing the image with two LDA $C08B fixes the issue.

Excerpt from [apple2e.S](https://github.com/davidgiven/cpm65/blob/master/src/bios/apple2e.S)

sta MEM_BANKING+0xb     ; R/W 0xe000 RAM; bank 1 in 0xd000 <- should be changed to lda MEM_BANKING+0xb
sta MEM_BANKING+0xb     ; yes, I'm sure <- should be changed to lda MEM_BANKING+0xb

**Comment by univta0001** [comment]
As far as i know it should not work in the real hardware as bank switching will not be enabled with the STA commands. Using STA command, the wrt count will not reached 2 to cause the High RAM to be set.

![image](https://github.com/davidgiven/cpm65/assets/25102440/b3374bd8-156a-4f80-9a5b-774ce45e36b1)

**Comment by davidgiven** [comment]
Sorry for the long delay --- but it seems this got fixed in April: https://github.com/davidgiven/cpm65/blob/master/src/bios/apple2e.S#L68 I think you must have found an old version from somewhere... so, closing.

**Comment by davidgiven** [comment]
No it isn't. Misread your message, sorry!
