### ISSUE TITLE
Failing to assemble .COMs on macOS (13.6)

### ISSUE THREAD

**Issue by markjreed** [davidgiven/cpm65#73]
The order of assembly arguments in the Makefile doesn't work on macOS.  `bin/cpmemu $(OBJDIR)/asm.com -pA=$(dir $<) -pB=$(dir $@) ...` results in the creation of files named `-pA=dir` and `.pB=dir`.  It works if you move the `-p` options in front of the name of the file to execute: `bin/cpmemu -pA=$(dir $<) -pB=$(dir $@) $(OBJDIR)/asm.com ...`

**Comment by davidgiven** [comment]
Interesting. That's a getopt incompatibility between GNU getopt and BSD getopt --- I'll fix it. Thanks.

**Comment by davidgiven** [comment]
This should now be fixed as a side effect of other changes.
