### ISSUE TITLE
ccp internal "ren" does not work

### ISSUE THREAD

**Issue by SvOlli** [davidgiven/cpm65#79]
When I try
`ren ls.com l.com`
the drive works for quite some time, but does not seem to change anything. `dir` still shows "ls.com".

BTW: Is there a way to move a file from one "user partition" to anonther?

**Comment by davidgiven** [comment]
The CP/M rename signals syntax is weird. Try `ren newfile=ls.com`.

What you entered should have produced an error, though. I'll need to take a look at that.

Re user partitions: no. It's one of the things which make user numbers wretched.

**Comment by SvOlli** [comment]
Okay, even
`ren newname oldname`
works.
